server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://b41d593e901c18:2ba93d2f@us-cdbr-east-04.cleardb.com/heroku_51f76287df095ba?reconnect=true
    username: b41d593e901c18
    password: 2ba93d2f
    hikari:
      max-lifetime=600000
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: poodle.rmq2.cloudamqp.com
    username: qtwqbndk
    password: pmlbqf9DkBOL4g77VUgfRNHc8lOiNDdw
    virtual-host: qtwqbndk

jwt:
  secret: 5ebe2294ecd0e0f08eab7690d2a6ee69
